// @ts-check
import { readdirSync, readFileSync } from 'node:fs';
import { defineConfig } from 'astro/config';
import tailwindcss from '@tailwindcss/vite';
import mdx from '@astrojs/mdx';
import react from '@astrojs/react';
import sitemap from '@astrojs/sitemap';

import cloudflare from '@astrojs/cloudflare';

const SITE_URL = 'https://poopcheck.app';

/** Generated by `npm run images`. */
const bristolImages = JSON.parse(readFileSync('./src/data/bristol-images.json', 'utf8'));

/** @param {string} dir */
const slugsIn = (dir) =>
  readdirSync(dir)
    .filter((f) => /\.mdx?$/.test(f))
    .map((f) => f.replace(/\.mdx?$/, ''));

const BLOG_SLUGS = new Set(slugsIn('./src/content/blog'));
const GUIDE_SLUGS = new Set(slugsIn('./src/content/guides'));

/**
 * Each chart plus its light printable variant — both are separate indexable assets.
 *
 * @param {string} slug
 * @param {string} title
 * @param {string} caption
 */
const chart = (slug, title, caption) => [
  { url: `${SITE_URL}/images/charts/${slug}.png`, caption, title },
  {
    url: `${SITE_URL}/images/charts/${slug}-printable.png`,
    caption: `${caption} Printable white-background version.`,
    title: `${title} (printable)`,
  },
];

const CHARTS = {
  bristol: [
    {
      url: `${SITE_URL}/images/charts/bristol-stool-chart.png`,
      caption:
        'The Bristol Stool Chart — all 7 stool types with pictures, from Type 1 (severe constipation) to Type 7 (diarrhea).',
      title: 'Bristol Stool Chart',
    },
  ],
  color: chart(
    'poop-color-chart',
    'Poop Color Chart',
    'The Poop Color Chart — what brown, green, yellow, pale, red and black stool mean, and which colors need a doctor.'
  ),
  baby: chart(
    'baby-poop-color-chart',
    'Baby Poop Color Chart',
    'Baby Poop Color Chart — what every diaper color means from meconium to solids, and the three that need a doctor.'
  ),
  fiber: chart(
    'high-fiber-foods-chart',
    'High-Fiber Foods Chart',
    'High-Fiber Foods Chart — 20 foods ranked by grams of dietary fiber per serving, with the daily target marked.'
  ),
  fodmap: chart(
    'low-fodmap-food-list',
    'Low FODMAP Food List',
    'Low FODMAP Food List — low and high FODMAP foods across seven categories for the elimination phase.'
  ),
};

/** @type {Array<{url: string, caption: string, title: string}>} */
const typeImages = bristolImages.images.map((/** @type {any} */ i) => ({
  url: `${SITE_URL}${i.file}`,
  caption: i.alt,
  title: `Bristol Stool Type ${i.type} — ${i.name}`,
}));

/**
 * Attach an <image:image> block to each URL so Google Images can discover
 * artwork it would otherwise only find by crawling the page HTML.
 *
 * @param {string} loc
 */
function imagesForUrl(loc) {
  const path = new URL(loc).pathname;

  if (path === '/bristol/') return [...CHARTS.bristol, ...typeImages];
  if (path === '/poop-color-chart/') return CHARTS.color;
  if (path === '/baby-poop-color-chart/') return CHARTS.baby;
  if (path === '/high-fiber-foods-chart/') return CHARTS.fiber;
  if (path === '/low-fodmap-food-list/') return CHARTS.fodmap;
  if (path === '/poop-pictures/') return [...CHARTS.bristol, CHARTS.color[0], ...typeImages];

  const bristolType = path.match(/^\/bristol\/type-(\d)\/$/);
  if (bristolType) {
    const match = typeImages.find((i) => i.title.includes(`Type ${bristolType[1]} `));
    return match ? [match, ...CHARTS.bristol] : CHARTS.bristol;
  }

  const post = path.match(/^\/poopcheck-blog\/([^/]+)\/$/);
  if (post && BLOG_SLUGS.has(post[1])) {
    return [{ url: `${SITE_URL}/images/og/blog/${post[1]}.png` }];
  }

  const guide = path.match(/^\/guides\/([^/]+)\/$/);
  if (guide && GUIDE_SLUGS.has(guide[1])) {
    return [{ url: `${SITE_URL}/images/og/guides/${guide[1]}.png` }];
  }

  return [];
}

export default defineConfig({
  site: 'https://poopcheck.app',
  output: 'static',
  trailingSlash: 'always',

  redirects: {
    // Page-level redirects. Old Squarespace URLs are now real pages at the same paths
    // (/about-poopcheck, /ai-poop-analyzer, /ai-stool-analysis-technology, /faq,
    // /poopcheck-blog) to preserve SEO equity. Redirects below cover only paths
    // that don't have a 1:1 page in the new site.
    '/playground': '/demo/',
    '/track-your-health': '/features/poop-tracking/',
    '/privacy-policy': '/privacy/',
    // Health Data Consent page removed; its material is covered by the Privacy Notice
    '/health-data-consent': '/privacy/',
    '/contact-us': '/support/',
    '/cart': '/',

    // Internal-to-canonical: /about (removed) → /about-poopcheck (the SEO URL)
    '/about': '/about-poopcheck/',

    // Legacy /blog/ prefix → canonical /poopcheck-blog/ (root + any sub-slug)
    '/blog': '/poopcheck-blog/',
    '/blog/[...slug]': '/poopcheck-blog/[...slug]',

    // Old blog post with matching new content (different slug)
    '/poopcheck-blog/bristol-stool-chart-explained-your-guide-to-stool-health': '/poopcheck-blog/bristol-stool-chart-types-explained/',

    // Mucus in Stool — moved from gibberish Squarespace slug to clean slug
    '/poopcheck-blog/yzaivbi2a54j7jy72mcb852emg02vg': '/poopcheck-blog/mucus-in-stool/',

    // Old blog posts without ported equivalents → blog index (Big Breakfast + Bioengineered Probiotics skipped in migration)
    '/poopcheck-blog/how-a-big-breakfast-diet-boosts-appetite-control-and-gut-health': '/poopcheck-blog/',
    '/poopcheck-blog/bioengineered-probiotics-a-new-frontier-in-gut-health-and-diabetes-care': '/poopcheck-blog/',

    // Old category redirects → blog index
    '/poopcheck-blog/category/Bristol+Stool+Chart': '/poopcheck-blog/',
    '/poopcheck-blog/category/Diet+%26+Nutrition': '/poopcheck-blog/',

    // Tag pages were removed (198 of 309 sitemap URLs, 157 of them listing a
    // single post, zero clicks in three months). Astro's `redirects` can't map
    // a dynamic source onto one static destination, so the wildcard rule that
    // retires them is appended to _redirects in scripts/patch-wrangler.mjs.

    // /category/app-updates/ had zero posts; categories now derive from real
    // post counts, so the route no longer generates it.
    '/poopcheck-blog/category/app-updates': '/poopcheck-blog/',
  },

  vite: {
    plugins: [tailwindcss()],
    server: {
      allowedHosts: true,
    },
  },

  prefetch: {
    prefetchAll: true,
    defaultStrategy: 'viewport',
  },

  integrations: [
    mdx(),
    react(),
    sitemap({
      // Exclude the API routes only. The old `includes('/api/')` also swallowed
      // the real marketing page /business/api/, which was live but missing from
      // every sitemap we ever submitted.
      filter: (page) => !new URL(page).pathname.startsWith('/api/'),
      changefreq: 'weekly',
      priority: 0.7,
      serialize(item) {
        const img = imagesForUrl(item.url);
        return img.length ? { ...item, img } : item;
      },
    }),
  ],

  markdown: {
    shikiConfig: {
      theme: 'github-dark',
    },
  },

  adapter: cloudflare(),
});